<?xml version="1.0"?>
<!DOCTYPE classrooms [<!ELEMENT classrooms (classroom+, student?, carte*)><!ELEMENT carte (code)><!ELEMENT code (#PCDATA)><!ELEMENT classroom (#PCDATA)><!ELEMENT student (#PCDATA)>]>
<classrooms>
  <!-- <!DOCTYPE classrooms SYSTEM "exemple.dtd"> -->
  <classroom>AL</classroom>
  <classroom>IABD</classroom>
  <classroom>MOC</classroom>
  <classroom>IBC</classroom>
  <coffee>sfef</coffee>
  <student name="swann" />
  <carte>
    <!-- NOK <code>2020</code> -->
    <!-- OK <codee>2020</codee> -->
  </carte>
</classrooms>