=== SwannHERRERA/xml-editor/xml-test/dtd-profondeur-multiple.dtd
<!ELEMENT classrooms (classroom+, student?, carte)>
<!ELEMENT carte (code)>
<!ELEMENT code (prefix, suffix)>
<!ELEMENT prefix (valeur*)>
<!ELEMENT suffix (valeur+)>
<!ELEMENT valeur (valeur-interne)>
<!ELEMENT valeur-interne (#PCDATA)>
<!ELEMENT classroom (#PCDATA)>
<!ELEMENT student (#PCDATA)>
<!ATTLIST student name CDATA #IMPLIED>

=== SwannHERRERA/xml-editor/xml-test/profondeur-multiple.xml
<?xml version="1.0"?>
<!DOCTYPE classrooms SYSTEM "./xml-test/dtd-profondeur-multiple.dtd">
<classrooms>
  <classroom>AL</classroom>
  <classroom>IABD</classroom>
  <classroom>MOC</classroom>
  <classroom>IBC</classroom>
  <classroom>IBC</classroom>
  <student name="swann" />
  <carte>
    <code>
      <prefix>
        <valeur>
          <valeur-interne>12</valeur-interne>
        </valeur>
      </prefix>
      <suffix>
        <valeur>
          <valeur-interne>13</valeur-interne>
        </valeur>
      </suffix>
    </code>
  </carte>
</classrooms>
